# Generated by Django 5.2.5 on 2026-08-09 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.UUIDField()),
                ("event_id", models.UUIDField()),
                ("notification_type", models.CharField(max_length=100)),
                ("recipient_id", models.UUIDField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In app"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["property_id", "status"],
                        name="notificatio_propert_f942e1_idx",
                    ),
                    models.Index(
                        fields=["recipient_id", "status"],
                        name="notificatio_recipie_dc877a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="queued", max_length=30)),
                ("response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationintent",
                    ),
                ),
            ],
        ),
    ]
