# Generated by Django 6.1 on 2026-08-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationintent",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
