# Generated by Django 5.2.5 on 2026-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_status_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ready_by_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
