# Generated by Django 5.2.5 on 2026-08-09 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.UUIDField(db_index=True)),
                ("number", models.CharField(max_length=20)),
                ("occupied", models.BooleanField(default=False)),
                ("guest_name", models.CharField(blank=True, max_length=160)),
                ("folio_reference", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property_id", "number"), name="unique_property_room"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_id", models.UUIDField(db_index=True)),
                ("runner_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("no_answer", "No answer"),
                            ("returned", "Returned"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="hotel.room",
                    ),
                ),
            ],
        ),
    ]
