# Generated by Django 5.2.5 on 2026-08-09 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.UUIDField(db_index=True)),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=120)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(max_length=96)),
                ("payload", models.JSONField(default=dict)),
                ("correlation_id", models.CharField(db_index=True, max_length=96)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "key",
                    models.CharField(max_length=160, primary_key=True, serialize=False),
                ),
                ("property_id", models.UUIDField(db_index=True)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=60)),
                ("entity_id", models.CharField(max_length=96)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=120)),
                ("aggregate_id", models.CharField(max_length=96)),
                ("payload", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["published_at", "created_at"],
                        name="venue_platf_publish_52d449_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(max_length=100)),
                ("available", models.BooleanField(default=True)),
                ("prep_station", models.CharField(default="main", max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="venue_platform.property",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["property", "available", "category"],
                        name="venue_platf_propert_4211bc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("kitchen", "Kitchen"),
                            ("waiter", "Waiter"),
                            ("cashier", "Cashier"),
                            ("front_desk", "Front desk"),
                            ("runner", "Runner"),
                            ("admin", "Admin"),
                        ],
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="venue_platform.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "user"), name="unique_property_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("room", "Room"),
                            ("counter", "Counter"),
                        ],
                        max_length=24,
                    ),
                ),
                ("qr_token", models.CharField(max_length=96, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("capacity", models.PositiveIntegerField(default=2)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="venue_platform.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "label"), name="unique_location_label"
                    )
                ],
            },
        ),
    ]
