# Generated by Django 6.1 on 2026-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
