# Generated by Django 6.1 on 2026-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue_platform", "0002_menuitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymembership",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
