# Generated by Django 5.2.5 on 2026-08-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venue_platform", "0004_ingredient_recipeingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="menu_item",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
    ]
