# Generated by Django 6.1 on 2026-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue_platform", "0005_remove_recipeingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="dietary_preference",
            field=models.CharField(
                choices=[("veg", "Veg"), ("non_veg", "Non-Veg"), ("vegan", "Vegan")],
                default="veg",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="preparation_time",
            field=models.IntegerField(
                blank=True, help_text="Time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="spice_level",
            field=models.IntegerField(blank=True, help_text="1 to 5", null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
